### ISSUE TITLE
v0.11.0 Exception: HttpError: Invalid tree info

### ISSUE THREAD

**Issue by JulyWitch** [fjogeleit/yaml-update-action#513] opened 2022-10-18 12:49 UTC
I'm getting this exception after the v0.11.0 release. The YAML file looks fine but the action throws this exception.
After downgrading to v0.10.0 It works fine.

<img width="471" alt="Screen Shot 2022-10-18 at 4 15 53 PM" src="https://user-images.githubusercontent.com/56545166/196433142-258c6bf4-c96e-4640-8a4b-6b49bd267856.png">

**Comment by fjogeleit** [comment] 2022-10-18 12:52
hey, thanks for reporting. Can you provide your basic values? To check what the issue could be

**Comment by fjogeleit** [comment] 2022-10-20 10:54
@JulyWitch can you provide your values or basic example how do you configured the action? I am not able to reproduce your issue currently.

**Comment by sspakush** [comment] 2022-10-26 10:01
We face same problem. It appears when value in "valueFile" and "value" variable not changed.

**Comment by fjogeleit** [comment] 2022-10-26 14:19
So basically if no update would be necessary? Thanks I will check that

**Comment by sspakush** [comment] 2022-10-26 16:20
@fjogeleit 
yes, in our case if no update - we need to deploy version which is indicated in yaml. We need it for release the same versions at all environments

**Comment by fjogeleit** [comment] 2022-10-27 09:11
I fixed the check if an actual change happened, if not git processing is skipped and the error should be gone. It is released as `v0.11.1`

**Closed by fjogeleit** 2022-10-27 09:11 UTC
